spring:
  application:
    name: talents
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/employeemanager}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        default_schema: public
        enable_lazy_load_no_trans: true
        jdbc:
          time_zone: UTC
    open-in-view: false
    hibernate:
      ddl-auto: update
base:
  url: ${BASE_URL:api}